[package]
name = "kern"
version = "0.1.0"
authors = ["Matthew MacLeod <matt@umm.io>"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "0.1.4"
volatile = "0.1.0"
spin = "0.3.4"
